name: core_auth
description: "Core authentication package: login, session management, and secure storage"
version: 0.0.1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  core_domain:
    path: ../core_domain
  core_data:
    path: ../core_data
  meta: 1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  mocktail: 1.0.4

